version: 2.1

jobs:
  build-artifact:
    docker:
      - image: circleci/python:latest
    steps:
      - run: echo "Build"
  deploy-to-staging:
    docker:
      - image: circleci/python:latest
    steps:
      - run: echo "Deploy"

workflows:
  version: 2.1

  stage_workflow:
    jobs:
      - build-artifact:
          filters:
            branches:
              only: master
      - deploy-to-staging:
          filters:
            branches:
              only: master
          requires:
            - build-artifact