version: 2.1

jobs:
  build_artifact:
    docker:
      - image: circleci/python:latest
    steps:
      - run: echo "Build"
  deploy_to_staging:
    docker:
      - image: circleci/python:latest
    steps:
      - run: echo "Deploy"

workflows:
  version: 2.1

  stage_workflow:
    jobs:
      - build_artifact:
          filters:
            branches:
              only: master
      - deploy_to_staging:
          filters:
            branches:
              only: master
          requires:
            - build_artifact