version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - run: echo "Build"
  deploy:
    docker:
      - image: circleci/python:latest
    steps:
      - run: echo "Deploy"